### PR TITLE
Restore Windows compatibility

### PR DESCRIPTION
**Pull request by michaelsproul**
This is pull request restores compatibility on Windows.

I've got it working now ~~apart from 2 of the tests which I believe are related to an underlying issue with MDBX on Windows~~.

The main changes are:

* Revert 43a899c3e866c134b3053e45cd4e7ec0bb4150c6 to bring back CI and some `OsStr` conversions
* Abstract over enums being represented as either `i32` (Windows) or `u32` (Unix). This is the simplest workaround I could think of for https://github.com/rust-lang/rust-bindgen/issues/1907.

### CODE REVIEW

**Comment by michaelsproul** [comment]
I've been running CI on my fork here: https://github.com/michaelsproul/mdbx-rs/runs/4292559511?check_suite_focus=true

It's failing with really strange Windows errors that I can't repro locally. I'll come back to it.

**Comment by michaelsproul** [comment]
Ready for review!

I finally got the build to pass, although it involved rewriting`build.rs` to use CMake. This seems to be the [recommended](https://github.com/erthink/libmdbx#windows) way of building on Windows, and bypasses the weird compiler errors.

There's a successful CI run here on my fork: https://github.com/michaelsproul/mdbx-rs/actions/runs/1494594706. I expect it should pass when run again here.

**Comment by michaelsproul** [comment]
Building with CMake is now optional, enabled by default on Windows.

**Review by vorot93 — APPROVED** [review]
Thanks!

**Pull request merged**
